services:
    datatables.factory:
        class: Saturno\DataTablesBundle\Manager\TableFactory
        arguments: [@twig]
    filter_render:
        class: Saturno\DataTablesBundle\Twig\TableExtension
        arguments: [@kernel, @twig]
        tags:
          - {name: twig.extension}
